lr_schedule: linear
initialization_strategy: 'zero'
n_steps: 8
learning_rate: 0.00096
ent_coef: 0.0
vf_coef: 0.4
max_grad_norm: 0.5
rms_prop_eps: 1.3210493147783147e-05
use_rms_prop: false
use_sde: True
sde_sample_freq: 97
normalize_advantage: false
gae_lambda: 0.9
net_arch_width: 64
net_arch_depth: 2
activation_fn: tanh
ortho_init: true
initialization_strategy: 'perfect'