    max_ingredients: 7
    action_scaling_factor: 20
    n_steps: 100
    gamma: 0.9611849566813905
    learning_rate: 2.7588161412656076e-05
    lr_schedule: constant
    ent_coef: 0.0003636763254215976
    vf_coef: 0.11804916359256488
    max_grad_norm: 5
    gae_lambda: 0.98
    rms_prop_eps: 1.3210493147783147e-05
    use_rms_prop: False
    use_sde: True
    sde_sample_freq: 97
    normalize_advantage: False
    ortho_init: True
    activation_fn: tanh
    net_arch_width: 256
    net_arch_depth: 1