gamma: 0.99
n_steps: 512
batch_size: 128
n_epochs: 20
learning_rate: 3.0e-05
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5
clip_range: 0.4
clip_range_vf: null
gae_lambda: 0.9
normalize_advantage: null
rollout_buffer_class: null
rollout_buffer_kwargs: null
target_kl: 0.039520969364598375
stats_window_size: null
net_arch_width: 256
net_arch_depth: 2
activation_fn: tanh
ortho_init: true
lr_schedule: cosine
learning_rate: 3.0e-05

    # if lr_schedule_type == "linear":
    #     learning_rate = linear_schedule(learning_rate)
    # elif lr_schedule_type == "cosine":
    #     learning_rate = cosine_annealing_schedule(learning_rate)
    # elif lr_schedule_type == "step":
    #     learning_rate = step_decay_schedule(learning_rate)
    # elif lr_schedule_type == "exponential":
    #     learning_rate = exponential_decay_schedule(learning_rate)
    # return learning_rate
# V3 TRIAL 1

# batch_size: 512
# n_steps: 1024
# gamma: 0.5
# learning_rate: 0.06251527472735463
# lr_schedule: constant
# ent_coef: 0.010304982694663524
# clip_range: 0.3
# n_epochs: 1
# gae_lambda: 1.0
# max_grad_norm: 0.6
# vf_coef: 0.5732056160403549
# clip_range_vf: null
# normalize_advantage: null
# target_kl: 0.062405643023600584
# ortho_init: true
# activation_fn: tanh
# net_arch_width: 256
# net_arch_depth: 4
# clip_obs: 10
# norm_reward: true



# batch_size: 512
# n_steps: 512
# gamma: 0.5
# learning_rate: 0.009921904100395628
# lr_schedule: constant
# ent_coef: 0.005071762410956447
# clip_range: 0.3
# n_epochs: 20
# gae_lambda: 1.0
# max_grad_norm: 0.6
# vf_coef: 0.46175669421399
# clip_range_vf: null
# normalize_advantage: null
# target_kl: 0.09407519349509248
# ortho_init: null
# activation_fn: tanh
# net_arch_width: 64
# net_arch_depth: 3
# clip_obs: 10
# norm_reward: true


# batch_size: 8
# n_steps: 256
# gamma: 0.98
# learning_rate: 8.024735850749812e-05
# lr_schedule: linear
# ent_coef: 2.7330665706503955e-08
# clip_range: 0.3
# n_epochs: 1
# gae_lambda: 1.0
# max_grad_norm: 0.7
# vf_coef: 0.8022704141761053
# clip_range_vf: null
# normalize_advantage: true
# target_kl: 0.02360824534777503
# ortho_init: null
# activation_fn: tanh
# net_arch_width: 16
# net_arch_depth: 2
# clip_obs: 10
# norm_reward: null
