gamma: 0.99
n_steps: 512
batch_size: 128
n_epochs: 20
learning_rate: 3.0e-05
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5
clip_range: 0.4
clip_range_vf: null
gae_lambda: 0.9
normalize_advantage: null
use_sde: true
sde_sample_freq: 4
rollout_buffer_class: null
rollout_buffer_kwargs: null
target_kl: 0.039520969364598375
stats_window_size: null
net_arch_width: 256
net_arch_depth: 2
activation_fn: tanh
ortho_init: true
lr_schedule: linear
initialization_strategy: 'perfect'